data_set_name:
  housing_file: housing.csv
  test_file: test.csv
  training_file: train.csv
models:
  catencoder_file: onehotencoder.pkl
  final_model_file: finalmodel1.pkl
  full_pipln_transform: comb_transform.pkl
  imputer_file: imputer1.pkl
  scaler_file: scaler.pkl
